name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.MY_SECRET_CLD_KEY }}
          project_id: deploy-cloud-01

      # Step 3: Set up gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: deploy-cloud-01

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/deploy-cloud-01/cloudrun/dev:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/deploy-cloud-01/cloudrun/dev:latest

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy vjya \
            --image us-central1-docker.pkg.dev/deploy-cloud-01/cloudrun/dev:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project deploy-cloud-01 \
            --service-account cloud-run-runtime@deploy-cloud-01.iam.gserviceaccount.com \
            --timeout=600s
